### ISSUE TITLE
Error: file has no sequences defined (mode='rb') 

### ISSUE THREAD

**Issue by soumyarao86** [ryanlayer/samplot#103]

**Comment by soumyarao86** [comment]
Hi, I am very excited to try this tool. I installed it through conda and the samplot -h command works well. However when I try to run it with the test files (which I copied from here since these were not automatically downloaded while installation) I get the following error:

Error: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False

**Comment by jbelyeu** [comment]
can you double-check that the data files downloaded correctly (with samtools view or igv)? Sounds like they're empty or corrupted.

**Comment by soumyarao86** [comment]
Hi, thanks for the clue. These were empty files. It worked on one of my files!
