### ISSUE TITLE
Is the csi index not suitable for samplot?

### ISSUE THREAD

**Issue by Jiny000** [ryanlayer/samplot#107]
Hi,
I used samplot to plot SV image.For bam files were too large, I used below command to make index,and get the .csi file:
```sh
samtools index -c sample.bam
```
However,when I used samplot ,it is report an error(The csi file and bam file are in the same path.):
```sh
samplot plot: error: alignment file ../sample.bam has no index
```
I wonder why with the csi file，the soft is still error?Is the .csi index not appropriate for samplot as index ?What should I do for it?Index was created by samtools 1.9  with using htslib 1.9.The version of samplot I used is samplot 1.0.14.

Sincerely,
Jingyao

**Comment by jbelyeu** [comment]
This was an oversight and is fixed in the upcoming version 1.0.15. Should be available from conda once it passes the testing/review process (within a day or two most likely). Thanks for letting us know
