### ISSUE TITLE
Support reading SAM files from remote [AWS/GCS]  buckets

### ISSUE THREAD

**Issue by SHuang-Broad** [ryanlayer/samplot#109]
Hi,

I am interested in using SAMPlot for visualizing and inspecting our SV calls, with both short paired reads and PB/ONT reads.

However, reading the documentation leads me to believe that currently the tool doesn't support reading from remote locations yet, specifically, SAM/CRAM/BAM files stored in (access-controlled) AWS/GCS buckets.

So I'm wondering if you have plans implementing this feature.

Thank you!
Steve

**Comment by jbelyeu** [comment]
Glad you're interested, Steve. Right now we're not planning on implementing that feature (although we happily accept pull requests!). My solution for that use case is to use samtools to slice out the regions I'm interested in and download the smaller resulting alignment file. Hope that helps!

**Comment by SHuang-Broad** [comment]
Thanks for the reply, Jon!

Now if I'm interested in investigating further, would you mind pointing me to where to start looking?
The main python script `samplot.py` seems fairly large.

Thanks!
Steve

**Comment by jbelyeu** [comment]
Sure. Search that file for `pysam.AlignmentFile`. Those 4 lines generate the iterators to read the alignment files

**Comment by SHuang-Broad** [comment]
Thanks!
I'll look into that.
Closing this.
