### ISSUE TITLE
Interchromosomal events

### ISSUE THREAD

**Issue by pdiakumis** [ryanlayer/samplot#11]
Ryan, 
Awesome tool. Is there any support for interchromosomal/complex events (or any future plans)? Can't see anything in the SV-plaudit paper. 
For example, svviz has something like this: http://svviz.readthedocs.io/en/latest/visualizations.html#complex-variants

Cheers - Peter

**Comment by ryanlayer** [comment]
We are working toward supporting interchromosomal events, but it is a little ways out. Complex event is an interesting idea. We could put multiple SVs on the top bar then give the BAM data for the full regions. I am not sure how we would do that from a VCF, but I could imagine passing in the SV details as a csv. Thanks for the suggestion.

**Comment by ryanlayer** [comment]
This is now done.
