### ISSUE TITLE
BAM index cannot be found

### ISSUE THREAD

**Issue by biozzq** [ryanlayer/samplot#110]
Dear All,

Very nice tool. During test, I found the bai index must be named $sample.bam.bai but cannot be $sample.bai. If possible, I hope you can add this feature.

Sincerely,
Zheng Zhuqing

**Comment by jbelyeu** [comment]
We've attempted to follow the standard naming convention (described in the context of IGV at http://software.broadinstitute.org/software/igv/book/export/html/93, quote below). Perhaps adding a symbolic link to the index file using the standard naming convention could solve your issue?


"...index files follow a specific naming convention. Specifically,  a BAM index file should be named by appending .BAI to the bam file name. A SAM index filename is created by appending .SAI."

**Comment by mjohnson11** [comment]
Hi! I am having this same issue. Thanks for the symlink workaround idea. For what it's worth I think probably a lot of people will have this problem bc it seems like GATK/Picard now follows a sample.bam -> sample.bai convention. I got there via SortSam (CREATE_INDEX=true), but it is more clearly documented for BuildBamIndex here: https://gatk.broadinstitute.org/hc/en-us/articles/360037057932-BuildBamIndex-Picard- .
