### ISSUE TITLE
read placement changes with different flags

### ISSUE THREAD

**Issue by earosenthal** [ryanlayer/samplot#122]
The placement of the paired reads changes when I include different flags. For example removing the labels (-n MOMID DADID PROBAND) results in figures that have paired reads at different heights and different horizontal positions. However, the X-axis and both Y-axes stay the same. The figure below shows one such example, with and without including a lable. 

My computing environment is Linux/CentOS7/x86_64. using the following versions: python/3.7.7, numpy/1.19.2, matplotlib/3.2.1, pysam/0.16.0.1 and samplot/1.0.1.

Please let me know if you have any questions or suggestions, and thanks for your time.
![m_merged](https://user-images.githubusercontent.com/6345017/100894216-de4dd380-3481-11eb-839a-da9f7166f669.png)

**Comment by jbelyeu** [comment]
Concordant reads are subsampled by default in samplot, so any reads that aren't identified by insert distance or pair order as discordant may not appear in a given samplot image (customizable using the `--max_depth` flag). The different X and Y positions of reads you see are therefore different reads that happen to be selected for plotting. Notice that the red reads, which have been identified as discordant by pair order, are in the same places, while the grey reads, which appear to be normal concordant reads, are in different places.
