### ISSUE TITLE
Plotting coverage only

### ISSUE THREAD

**Issue by mgonzalezporta** [ryanlayer/samplot#125]
Running the following command:

```
samplot plot \
    -n WHB4409 \
    -b chr10_126098573_126102616.bam \
    -o chr10_126088573_126112616.png \
    -c chr10 \
    -s 126088573 \
    -e 126112616 \
    -t DEL \
    --coverage_only
```

Returns a plot with left + right y axis: 

![chr10_126088573_126112616](https://user-images.githubusercontent.com/1401387/103877901-a8e77600-5110-11eb-9517-917f2537b055.png)

Is it possible to plot a single y axis with coverage?

Thanks,

**Comment by ryanlayer** [comment]
That should be pretty easy to do. We will work on it. Thanks for the
suggestion.

**Comment by Rohit-Satyam** [comment]
What window size is used by samplot for plotting coverage? or does it plot per base coverage @jbelyeu
