### ISSUE TITLE
removing overlap ("1e6"---scaling for y -axis insert size) with sample names 

### ISSUE THREAD

**Issue by am8265** [ryanlayer/samplot#132]
Hello Authors,

Thank you for this awesome tool! Could you please guide in regard to what parameters to use/may be a feature to add --
to adjust the sample names (e.g. SchizClinB42 and other names below) so as NOT to overlap with the scaling "1e6" on y-axis.The example figure is attached. Is there a way to 1) move the sample names towards right or 2) removing the "1e6" by multiplying with values on y-axis ? I have tried with some irrelevant parameters (e.g. --yaxis_label_fontsize and --legend_fontsize) but doesn't help.

![17_30526767_34318994_DEL SchizClinB42 123677 withCtrl](https://user-images.githubusercontent.com/21180898/113799565-4f98de00-9723-11eb-99db-5ff4c5e406c1.png)

Thank you for the help and please let me know if you have additional questions.

**Comment by jbelyeu** [comment]
This looks like a bug. I'm not certain what's going on but will address it in a few days. Can you share your samplot version?

**Comment by jbelyeu** [comment]
as a side note, does this still happen if you set the SV type with the -t option?

**Comment by am8265** [comment]
@jbelyeu samplot 1.1.0 is being used. Here is the image regenerated with -t DEL option (still 1e^6 persists for the sample in the top)
![17_30526767_34318994_DEL test png SchizClinB42 123677 withCtrl](https://user-images.githubusercontent.com/21180898/113919584-c381c780-97b1-11eb-8221-86146db555a5.png)

I haven't dig into the code yet, if samplot uses matplotlib, then this may be worth looking into --

https://stackoverflow.com/questions/28371674/prevent-scientific-notation-in-matplotlib-pyplot

**Comment by jbelyeu** [comment]
Good find, I actually also just looked at that and added the fix. I'll let you know as soon as it's through testing, although it will likely be a day or two before it's up on conda (can install from the repo sooner, of course)
