### ISSUE TITLE
csi index for gff3.gz not accepted by samplot

### ISSUE THREAD

**Issue by lentil824** [ryanlayer/samplot#134]
Hi there,
I can only generate csi index for my annotation file due to the size limit of tbi, however, samplot will produce an error message: missing .tbi index file. Wondering how to get around this issue?

Thanks,
Susan

**Comment by jbelyeu** [comment]
What samplot version are you using? This should be corrected as of v1.0.18 (current version is v1.1.3 and about to update to v1.1.5).

**Comment by lentil824** [comment]
I installed it yesterday through conda, so it should be the newest version, I assume. Power outage so can't access the server right now. I noticed a posted issue regarding bam file and bai index, but my issue is when using the annotation file.

**Comment by lentil824** [comment]
Btw, I used bam files with csi index and it worked. The issue only came out when I tried to add the annotation file with csi idex.

**Comment by jbelyeu** [comment]
Yep, you're right that this is still an issue for annotation files. I'll correct it
