### ISSUE TITLE
gene annotations overlapped together and not readable

### ISSUE THREAD

**Issue by LNGDingj** [ryanlayer/samplot#138]
Hello,  For some regions, the gene annotations were overlapped together and not readable. See the attached annotations. Is it possible to enlarge the subplots for annotations? Thank you!

![image](https://user-images.githubusercontent.com/53267778/116478447-164c1d80-a84c-11eb-89d3-05e96a11de09.png)
![image](https://user-images.githubusercontent.com/53267778/116478631-59a68c00-a84c-11eb-9265-391532993108.png)
![image](https://user-images.githubusercontent.com/53267778/116478681-70e57980-a84c-11eb-84a2-2cf6a4e30c68.png)
![image](https://user-images.githubusercontent.com/53267778/116478715-88246700-a84c-11eb-92b1-e6748b588460.png)

**Comment by nroak** [comment]
I'm trying to troubleshoot this same issue.

**Comment by jbelyeu** [comment]
Sorry about the delay. I'm working on a new release and should have it up next week with a solution to this problem.

**Comment by nroak** [comment]
Any update on this? We'd love to include a couple of samplot images in a manuscript draft.

**Comment by jbelyeu** [comment]
Apologies. This is coming very soon, I'm just working on final testing for several features in the new release. A few more days at most.

**Comment by ryanlayer** [comment]
If our timeline does not match yours, then we can help you modify your
annotation file to contain fewer transcripts or to remove some labels from
that transcripts file.  I am not sure if that fits your experimental goals,
but it could help with the overlapping features.

**Comment by nroak** [comment]
Thanks Jon and Ryan! It'll be very helpful if you could help me retain just the canonical transcript for now. That should be sufficient to serve immediate need. 
I look forward to the formal update in a few days as well.

**Comment by nroak** [comment]
Thank you very much for the quick fix and update to the tool. I'm able to scale the annotations as needed so that they don't overlap. Really appreciate your prompt response.

**Comment by LNGDingj** [comment]
Thanks so much!
