### ISSUE TITLE
Visualizing translocations

### ISSUE THREAD

**Issue by zhemingfan** [ryanlayer/samplot#154]
Hi samplot authors,

Your package looks awesome! I was wondering if it would be possible to visualize translocations by visualizing the breakpoints at two different chromosomes - side-by-side. 

Thanks.

**Comment by ryanlayer** [comment]
It is possible! Check out the publication for an example or this blog post

http://layerlab.org/2019/06/04/Samplot-improvement.html

**Comment by zhemingfan** [comment]
Thank you so much, closing this ticket.
