### ISSUE TITLE
Improve support for long reads

### ISSUE THREAD

**Issue by amwenger** [ryanlayer/samplot#16]
At the suggestion of @armintoepfer, I tried `samplot` on NGMLR alignments of PacBio data from Genome in a Bottle (HG002).  For these alignments, the `samplot` view is difficult for me to interpret.  It would be great if `samplot` could be modified to improve support for long-read data.  

To help, here are two examples:

## Deletion of hg19.chr1:58,343,211-58,343,535

[hg19 alignments](https://dl.dnanex.us/F/D/67g3qzYkBqkV5p9j69K6F609VQZF0X8g6qbKxVXF/hg19_chr1_58343117_58343622_deletion.bam) (350kb)

IGV view (see coverage dip and spanning reads)
![hg19_chr1_58343117_58343622_deletion-igv](https://user-images.githubusercontent.com/7155109/39148159-71ca0b74-46f0-11e8-860b-dd70dd3c99bf.png)

samplot view
![hg19_chr1_58343117_58343622_deletion-samplot](https://user-images.githubusercontent.com/7155109/39148163-7431313a-46f0-11e8-848d-4dcd86676175.png)

## Inversion of hg19.chr21:27,374,159-27,374,700

[hg19 alignments](https://dl.dnanex.us/F/D/604f3kFp5k4z95v41kVqKjvjgp796jQjBK4PQxQ9/hg19_chr21_27373431_27375410_inversion.bam) (633kb)

IGV view
![hg19_chr21_27373431_27375410_inversion-igv](https://user-images.githubusercontent.com/7155109/39148325-e1479070-46f0-11e8-9733-6211403298e1.png)

Gepard dotplot view
![hg19_chr21_27373431_27375410_inversion-dotplot](https://user-images.githubusercontent.com/7155109/39148334-e780a29c-46f0-11e8-83da-5440e4ba379e.png)

samplot view
![hg19_chr21_27373431_27375410_inversion-samplot](https://user-images.githubusercontent.com/7155109/39148344-edafbbd0-46f0-11e8-9284-eef40d08d24b.png)

**Comment by ryanlayer** [comment]
Pushed the long read support to master.
