### ISSUE TITLE
Cannot get the same image 

### ISSUE THREAD

**Issue by iastrovskaya** [ryanlayer/samplot#17]
Good evening,

   I wonder if you have an idea what is going on in my case:
  after I executing the first command line
  
```
samplot/src/samplot.py \
                 -n NA12878,NA12889,NA12890 \
                 -b samplot/test/data/NA12878_restricted.bam,samplot/test/data/NA12889_restricted.bam,samplot/test/data/NA12890_restricted.bam \
                    -o 4_115928726_115931880.png \
                  -c chr4 \
                   -s 115928726 \
                   -e 115931880 \
                    -t DEL
```

I got plot as follows
![4_115928726_115931880](https://user-images.githubusercontent.com/31016803/39339529-38ddda94-4997-11e8-8c19-c86076fc437e.png)

I run it in miniconda environment with python 3 and with python 2.7
matplotlib                2.2.2                     
numpy                     1.14.2                    
pysam                     0.14.1                    
scipy                     1.0.1

**Comment by ryanlayer** [comment]
Check out the latest update from jon.

**Comment by iastrovskaya** [comment]
Thank you!
