### ISSUE TITLE
Is it possible to output pdf

### ISSUE THREAD

**Issue by AJ211** [ryanlayer/samplot#170]
Hi,
  Thanks for developing samplot. I would like to know is it possible to export pdf images?

**Comment by pontushojer** [comment]
With `samplot plot` the file type is inferred from the output file (`-o` flag) extension. So something like `-o output.pdf` would output a PDF. Other accepted  formats are .svg and .eps. 

With `samplot vcf` there is a `-O` flag for selecting the output format.

**Comment by AJ211** [comment]
ok, thanks a lot for your quick reply.
