### ISSUE TITLE
Missing legend (?)

### ISSUE THREAD

**Issue by tuannguyen8390** [ryanlayer/samplot#171]
Hi there,

Thanks for developing this, such a great tools! However, for some reason I could not see the blue legend (inversion read) - I can see that in some examples posted on the Github manual. Any possible reason ?
<img width="892" alt="image" src="https://user-images.githubusercontent.com/47171822/201889577-cca7aa82-f8c6-4d0f-9b56-a99b9e6abddd.png">

Many thanks,

Tuan Nguyen

**Comment by mchowdh200** [comment]
I'd like to try to reproduce this issue on my end.  If possible, do you think you could subset the bam around that region +/-100k bases so that I can plot the SV and the flanking regions?

If not, I'll try to find some other long-read sample with inversions and see if I can reproduce it from that.

**Comment by tuannguyen8390** [comment]
Let's try this, 

[output.zip](https://github.com/ryanlayer/samplot/files/10099579/output.zip)

My Samplot command is

```
samplot plot -b output.bam -c 1 -s 39477269 -e 39530389 -t INV -o output.png
```
