### ISSUE TITLE
Empty html file from samplot vcf

### ISSUE THREAD

**Issue by shaghayeghsoudi** [ryanlayer/samplot#176]
Hi, I am trying to visualize my variants from long reads pacbio and nanopore. First I got an error message that noRG field in alignment and then I added the sample_ids flag and specified the sample name. This is my running command:
```
samplot vcf --vcf /oak/1_consensus_all_pacbio.vcf.gz \
            -d ./test/\
            -O png \
            --sample_ids 1 \
            -b /oak/1_q0l0_aln.bam > samplot_commands.sh
```

I get no error message but the html file is empty. I am wondering what is wrong and if there is any way I could fix this issue. Thanks

**Comment by shaghayeghsoudi** [comment]
when I added the --debug flag Ii get these tow types of warning:

```
Skipping DEL at 17:74987201-74987840, no plottable samples with matched alignment files
Skipping DEL at 17:74987519-74987839, no plottable samples with matched alignment files
Skipping INS at 17:75068265-75068266, INS type not supported
Skipping INS at 17:75099787-75099788, INS type not supported
Skipping INS at 17:75099788-75099789, INS type not supported
Skipping DEL at 17:75212203-75212282, no plottable samples with matched alignment files
Skipping DEL at 17:75235606-75236291, no plottable samples with matched alignment files
Skipping DEL at 17:75235947-75236290, no plottable samples with matched alignment files
Skipping DEL at 17:75241885-75242222, no plottable samples with matched alignment files
Skipping DEL at 17:75242052-75242221, no plottable samples with matched alignment files
Skipping DEL at 17:75245842-75245955, no plottable samples with matched alignment files
Skipping DEL at 17:75245897-75245959, no plottable samples with matched alignment files
Skipping INS at 17:75331939-75331940, INS type not supported
Skipping INS at 17:75352751-75352753, INS type not supported
Skipping INS at 17:75376339-75376340, INS type not supported
Skipping INS at 17:75376341-75376343, INS type not supported
...
```

**Comment by pontushojer** [comment]
What is the sample name in your VCF? `samplot` will look for VCF samples matching those you specified after `--sample_ids`, "1" in this case. 

There should however probably be a better error message if no VCF sample matches those specified after `--sample_ids` or found in the read group tag in the BAMs.

**Comment by shaghayeghsoudi** [comment]
Hey, thanks for your response. I did my alignment with minimap2 and noticed the RG filed is actually missing in my bam files. Also in my vcc files there is no SAMPLE name specified. It is just "SAMPLE". So not sure now, does this mean I can run the sample without having sample ID? I appreciate your response.

**Comment by shaghayeghsoudi** [comment]
Thanks so much @pontushojer for your replies. So one thing I noticed causing failure is my vcf format. We actually ran 5 different callers and combined them by CombiSV. I tried Samplot with one of my vcfs called by Sniffless and I got Samplot working so far. However, I do get warning messages about my Insertions. The error I am getting is: `INS type not supported`
This is examples from INS in my Sniffles vcf file:
```
chr1	533254	Sniffles2.INS.FS1	N	TCTCAGCAGCTCACGGTGTGGAAACTGCGACACTCACACGGGTGCCATCTCAGCAGCTCACGGTGTGGAAACTGCGACACTCACACGGGTGCCATCTCAGCAGCTCACGGTGTGGAAACTGCGACACTCACGCGGGTGCCGTCTCAGCAGCTCACGGTGTGGAAACTGCGACACTCACGCGGGTGCCGTCTCAGCAGCTCACGGTGTGGAAACTGCGACACTCACACGGGTGCCATCTCAGCAGCTCACGGTGTGGAAACTGCGACACTCACACGGGTGCCATCTCAGCAGCTCACGGTGTGGAAACTGCGACACTCACGCGGGTGCCGTCTCAGCAGCTCACGGTGTGGAAACTGCGACACTCACGCGGGTGCCG	60	PASS	PRECISE;SVTYPE=INS;SVLEN=376;END=533254;SUPPORT=9;COVERAGE=18,18,20,20,24;STRAND=+-;AF=0.450;STDEV_LEN=0.000;STDEV_POS=0.000;SUPPORT_LONG=0	GT:GQ:DR:DV	0/1:59:11:9
chr1	545928	Sniffles2.INS.11S1	N	TGCAGGAGAGGAGATGCCCAGGCCTGGCGGCCGGCGCACGCGGGTTCTCTGTGGCCAGCAGGCGGCGCTGCAGGAGAGGAGATGCCCAGGCCAGGCGGCCGGCGCACGCGGGTTCTCTGTGGCCAGCAGGCGGCGCTGCAGGAGAGGAGATGCCCAGGCCTGGCGGCCGGCGCACGCGGGTTCTCTGTGGCCAGCAGGCGGCGATGCAGGAGAGGAGATGCCCAGGCCTGGCGGCCGGCGCACGCGGGTTCTCTGTGGCCAGCAGGCGGCGCTGCAGGAGAGGAGATGCCCAGGCCAGGCGGCCGGCGCACGCGGGTTCTCTGTGGCCAGCAGGCGGCGCTGCAGGAGAGGAGATGCCCAGGCCTGGCGGCCGGCGCACGCGGGTTCTCTGTGGCCAGCAGGCGGCGA	60	GT	PRECISE;SVTYPE=INS;SVLEN=408;END=545928;SUPPORT=8;COVERAGE=48,46,46,50,50;STRAND=+-;AF=0.174;STDEV_LEN=0.000;STDEV_POS=0.000;SUPPORT_LONG=0	GT:GQ:DR:DV	0/0:25:38:8
```

So I am not sure what can be done to get this resolved? I really appreciate your help

**Comment by shaghayeghsoudi** [comment]
Sorry I had to re-open the issue again. It seems my tries to plot translocations fail due to this warning message: `variant length shorter than min_bp`
Is there any way I could fix this? specify min_bp flag? Thanks a lot
