### ISSUE TITLE
overlapping x and y axis labels

### ISSUE THREAD

**Issue by hagen-wende** [ryanlayer/samplot#201]
I just used samplot for the firsst time, but I do get overlapping x and y axis labels, how can I get rid of those? Or do you have any idea, whatss going on, this is version 1.3.0 ...

![grafik](https://github.com/user-attachments/assets/aa08e7c8-a86f-4895-8988-35389a4ced17)

**Comment by jbelyeu** [comment]
I've just attempted to recreate that issue and am not seeing it, so it's probably a problem with a specific version of a dependency in your system. In my installation, I'm running python 3.10.0, matplotlib 3.6.3, numpy==1.26.4, pysam 0.22.1, and jinja2 3.1.4. Perhaps you can retest with these versions and see if that resolves the problem?

**Comment by hagen-wende** [comment]
so this was a fresh install in an empty env using

`conda install bioconda::samplot`

versions in the env are:
```
python 3.12.4
matplotlib 3.9.1
numpy 2.0.1
pysam 0.22.1
jinja2 3.1.4
```

after reverting to the versions, you mention the isssue is gone. Thanks!
