### ISSUE TITLE
Normalized coverage?

### ISSUE THREAD

**Issue by iastrovskaya** [ryanlayer/samplot#21]
Dear Ryan,

  Are you considering to add option for showing normalized coverage in the plots? (for example, from XHMM)?

Thank you for the tool!
Irina

**Comment by ryanlayer** [comment]
I think this is an interesting idea. I am going to mark this an enhancement for now because it looks like quite a bit of work so it will be a while before I can get to it.

**Comment by ryanlayer** [comment]
This option now exists.
