### ISSUE TITLE
samplot saveFig() error with jagged image (many points on a line)

### ISSUE THREAD

**Issue by jbelyeu** [ryanlayer/samplot#22]
This is a known issue with the agg backend (see related thread here https://github.com/matplotlib/matplotlib/issues/5907). Actual line of the error is 792, but the problem is caused before saveFig. Agg does not allow a large number of points on a line.

I'm testing possible solutions

**Comment by jaesvi** [comment]
Hi,
I'm facing this problem, is there a fix? Or should I just skip this SV?
Thanks,
Jose

**Comment by jbelyeu** [comment]
I've had success plotting with Python 3.X.X instead of Python 2.X.X. Several fixes that I've attempted have been unsuccessful in handling this with 2.X.X. I think going forward the best call is going to be using 3.X.X for larger variants, although I'm sure it'll stop working at some size with 3.X.X as well. In addition, variants that fail in 2.X.X take a long time to render (just due to size) in 3.X.X, sometimes as much as an hour. If a variant is taking that long to render and is very large, samplot may not be able to handle it.
