### ISSUE TITLE
samplot.py: error: SV sv_type not given

### ISSUE THREAD

**Issue by estolle** [ryanlayer/samplot#23]
Hi there

Thanks for the great tool. I seem to have troubles with running it without the -t option, as described in the bottom of the instructions.  I am getting an error (using the option works and plots)
samplot.py: error: SV sv_type not given

Since i kinda do exploratory assessments, I would like plots without the bars / type printed on top.

Is this a bug or am I using the option wrong.

My command:
/opt/samplot/src/samplot.py -c $SCF -s $START -e $END -b $BAMFILE.bam -o $BAMFILE.samplot.DEL.9.jpg -z 3 -d 100 -A /scratch/genomes/xxxxxxxxxx/lifted_cleaned.3.bed.gz

**Comment by ryanlayer** [comment]
Please try the latest version.
