### ISSUE TITLE
slow on high coverage regions (eg mtDNA)

### ISSUE THREAD

**Issue by drmjc** [ryanlayer/samplot#30]
Hi @ryanlayer,
firstly, awesome tool, I think it's helped find some small (~2Kb) DEL that I missed with other approaches. I'm using this to look at mtDNA deletions, where the depth is huge (4000x-20,000x depth depending on tissue), and the number of reads supporting the DEL can be very small due to purifying selection in blood.

samplot is really slow in this context & it didn't complete the visualisation of an 8Kb deletion overnight. If I subsample reads to about 300x then it works fast enough. But then I lose some of the precious few reads that support the DEL. I'm now pulling out split reads and discordant reads, then subsampling, then merging these three BAMs, but that's a bit of a pita to systematically look at lots of BAMs. 

I can't tell if it's the coverage estimation or the plotting of ~365,000 properly paired reads with typical insert sizes that's slowing this down.  

Do you have advice for speeding this up?

cheers,
Mark

**Comment by ryanlayer** [comment]
Have you tried using "-d" to limit the plotting of normal reads? This will not affect the splitters or discordant pairs, just the concordant pairs. "-d 100" should be good.

**Comment by drmjc** [comment]
thanks Ryan, that works like a charm.
