### ISSUE TITLE
BAM with Different Insert Size per Readgroup

### ISSUE THREAD

**Issue by nathanhaigh** [ryanlayer/samplot#31]
I have BAM files with different read groups, each may have different insert sizes. Does samplot take this into consideration in downsampling reads?

For example, the following plot shows there are insert sizes of 300 and 450 bp:

![image](https://user-images.githubusercontent.com/2037575/43351735-96b69780-9255-11e8-9c54-8ffa017f06c0.png)

In cases where larger insert sizes have been used in combination with smaller insert sizes, this would produce a more confused image of a deletion. Would plotting deviation from the insert size mean for a read group be a more useful metric than the insert size itself? I'm thinking back to AMOS Hawkeye days where they had a concept of compressed and stretched mates which differed from the global insert size mean.

**Comment by ryanlayer** [comment]
I like that idea, but we tried pretty to not make any decision about the given variant and the underlying data. Making a judgment about a given pair's insert versus "normal" insert approaches SV calling. That said, if you want to fork a branch that does this I would be happy to consider it. The other issue is that we would need to grab a few million reads before we could get "normal", which may slow things down quite a bit.

**Comment by nathanhaigh** [comment]
What about if the user supplied the mean insert size per readgroup upfront...that way you wouldn't need to calcultate this by sampling a few million reads?
I'll have a look into at what might be involved and what time commitment might be required. Under the pump at the moment!

**Comment by ryanlayer** [comment]
Ya that could work.
