### ISSUE TITLE
Linked read index error

### ISSUE THREAD

**Issue by jaesvi** [ryanlayer/samplot#35]
Hi,

When trying Samplot with 10X data crashes with:
> Traceback (most recent call last):
>   File "/home/cog/jvalleinclan/kloosterman/tools/SV-plaudit/Samplot/src/samplot.py", line 1244, in <module>
>     axs[j] = matplotlib.pyplot.subplot(inner_axs[hps[j]])
>   File "/hpc/local/CentOS7/cog/lib/python2.7/site-packages/matplotlib/gridspec.py", line 180, in __getitem__
>     raise IndexError("index out of range")
> IndexError: index out of range

when trying to plot DEL_2_219112325-219112776. Attached are 10kb slices of both tumor and normal BAM files (since I do not know which one is raising the error). This particular breakpoint has been plotted with illumina data without issue, so I guess it has to do with the linked reads. I was not succesful trying to fix it myself, so any hint would be appreciated.

Many thanks,
Jose

[tenX.TS.zip](https://github.com/ryanlayer/samplot/files/2358107/tenX.TS.zip)

.

**Comment by jbelyeu** [comment]
Should be fixed in #40. Please inform if problem persists.
