### ISSUE TITLE
Control Transcript Label Font Size

### ISSUE THREAD

**Issue by PedalheadPHX** [ryanlayer/samplot#37]
Is there a way to control the font size of the transcript labels, specifically those above each transcript in cornhuskblue color? In the test plot I'm working with these labels are bigger than any other font on the plot.  I suspect I would filter the transcript file so only one transcript per gene is shown to simplify the plot but having and option to only render one transcript for each gene might be a good option when multiple transcripts exist for the genes in the defined region.

Also, I'm guessing the predicted deletion size does not deal with overlapping deletions as seen in the attached plot.
![mmrf_2523_2_cdkn2c_del](https://user-images.githubusercontent.com/12407068/45920300-e304af00-be56-11e8-9a27-f82d9ea0a518.png)

Thanks for making the tool available it is very useful and the -d option is awesome for testing as it dropped a test from 30 minutes to 30 seconds roughly!

**Comment by jbelyeu** [comment]
Jonathan,
Thanks for trying our tool! I'm working on adding a few options similar to
this that'll be available within the next week or so. I can include this
option as well and will reach out to you as soon as it's ready so we can
make sure it works for your needs!

**Comment by jbelyeu** [comment]
Should be fixed via #40.

And yes, sorry I forgot to respond to the latter part, overlapping events are not considered. The evidence for an overlapping deletion is plotted just like anything else and the predicted variant is marked with the black bar regardless of evidence.
