### ISSUE TITLE
Feature Request: Make markers optional?

### ISSUE THREAD

**Issue by leiendeckerlu** [ryanlayer/samplot#47]
Hi there,

while the marker size can be reduced like this `--marker_size 0` it would be nice to have an option to not show at all any pair or split reads visualized in the output file and thus just get a coverage track figure.

Thank you!
Lukas

**Comment by jbelyeu** [comment]
We've added an option `--coverage-only` to accomplish this. Please let us know how that works for you

**Comment by leiendeckerlu** [comment]
Amazing, works like a charm! Many thanks! 

Just as a side note, it's currently implements as `--coverage_only` and not `--coverage-only` :)
