### ISSUE TITLE
VCF from Lumpy problem to plot with multiple samples

### ISSUE THREAD

**Issue by agcmartins** [ryanlayer/samplot#50]
Hi,
Using the Lumpy for a single sample I can plot without problem, but while using a multi-sample VCF I'm receiving the followed error. I also have a sample.bam.bai for for all samples in the folder, so I don't know if its a true "bamfile without index error"

Command:
$ samplot_vcf.sh -o plot -v allsample.vcf sample1_sorted.bam sample2.bam sample3_sorted.bam sample4_sorted.bam sample5_sorted.bam   

Error

Traceback (most recent call last):
  File "/home/agcmartins/bin/samplot.py", line 1155, in <module>
    range_max+1000):
  File "pysam/libcalignmentfile.pyx", line 1085, in pysam.libcalignmentfile.AlignmentFile.fetch
ValueError: fetch called on bamfile without index

**Comment by jbelyeu** [comment]
Sorry about that. I made a change a short time ago in the way arguments are handled, which changed the comma-separated list of input files to a space-separated list. Try this corrected version of [samplot_vcf.sh](https://raw.githubusercontent.com/jbelyeu/samplot/master/src/samplot_vcf.sh)

**Comment by agcmartins** [comment]
Thank you very much! It's working now!
Best regards,

**Comment by agcmartins** [comment]
Sorry, it is working but showing just one sample, the first one.

**Comment by jbelyeu** [comment]
This is working for me and looks very similar to your first command (but using the corrected `samplot_vcf.sh` script:

`samplot_vcf.sh -o temp/ -v temp.vcf 1691.bam 2781.bam`

If you try just plotting one of the BAMs that isn't working does it show something?

**Comment by agcmartins** [comment]
Hi,
Using
samplot_vcf_new.sh -o plot -v allsample.vcf  sample1.bam sampe2_sorted.bam sample3_sorted.bam sample4_sorted.bam sample5_sorted.bam

I got only plots for sample1 and when I change the order to start like "sample2_sorted.bam sampe3_sorted.bam sample4_sorted.bam sample5_sorted.bam sample1_sorted.bam" I get only plots for sample 2 and so on. I'm sending plot I got using sample 2 first. The order of sample columns  in VCF file is (1 to 5)

![dup_4_365968-368280](https://user-images.githubusercontent.com/43818139/49145721-5663ea80-f2f8-11e8-897e-0cc0dc45ca6f.png)

**Comment by jbelyeu** [comment]
I'm not sure what's going on here. If you're able to share data, I could try to replicate the error on my end. I would need a region from a couple of your bam files and the variant from that region that you're working with in the vcf (could be just the header of the vcf with first variant + that region in two bam files).

I would also suggest pulling the latest version of samplot, as this image appears to be mis-coloring some of the dup reads as black, which we recently fixed.

**Comment by jbelyeu** [comment]
The new samplot_vcf.py should resolve this problem. If the issue occurs again, please reopen
