### ISSUE TITLE
depth: draw vertical lines

### ISSUE THREAD

**Issue by brentp** [ryanlayer/samplot#53]
the depth plots draw interpolate between depths. should draw vertical lines, not diagonal. see attached image for example. can probably use plt.step() to fix this.
![dp](https://user-images.githubusercontent.com/1739/49616530-6752d280-f96e-11e8-940e-e504473df7c5.png)

**Comment by jbelyeu** [comment]
forgot to close issue, but this is fixed with the addition of `step='pre'` in call to `fill_between()`
