### ISSUE TITLE
intermediate data format

### ISSUE THREAD

**Issue by brentp** [ryanlayer/samplot#57]
if the plotting is done on a known, fixed, simple data format, we can use samplot for any type of data (not just bam).
I propose something like:
```Python
{'splits': [{'left': 1234, 'right': 3456, 'type': 'DEL'}],
 'discs': [...],
 depths: [33,22,25,...],
 depth_start: 1230
}
```
for each sample. we'll need additional things like sample names and titles but some variant of the above would be a start.

**Comment by jbelyeu** [comment]
Currently, read data is structured thus (outer list tracks sample for each data type):
read_data = {             
    "all_pairs" :      [ [{"read_id": PairedEnd}] ],            
    "all_splits":        [[{"read_id": SplitRead}]],
    "all_coverages":    [{"position" : [highqual_depth, lowqual_depth]}],
    "all_long_reads":   [[{"read_id": LongRead}]],
    "all_linked_reads": [{startposition: [[]]}]
 }

PairedEnd contains start, end, strand, molecular identifier, and haplotype
SplitRead contains start, end, strand, query position, molecular identifier, and haplotype
LongRead contains start, end, and a list of cigar operations/lengths (effectively, using the Alignment class in samplot)
all_linked_reads is an object that contains start positions -> lists of the read IDs for reads that belong to groups (nested list allows for multiple MI groups to begin at the same pos).

This seems like a pretty simple data structure to me, given the complexity of the data.
