### ISSUE TITLE
Gff3 not plotted

### ISSUE THREAD

**Issue by t-neumann** [ryanlayer/samplot#63]
Hi there,

as I had no gff3 files available, but GenBank format, I used bioperls `bp_genbank2gff3.pl` to convert features. Now I managed to create valid gff3 files and tabix them, but none of the features are displayed in the samplots.

Is there any way of finding out what's going on? There is also no error messages displayed, so I assume at least the features are extracted correctly.

I attached one gff file as example - this is the call I'm using.

```
samplot.py -r ref.fa -b $file -s 0 -e $end -c "$chr" -o ${out}.png -T ref.gff.gz --coverage_only
```
[ref.gff.gz](https://github.com/ryanlayer/samplot/files/3054116/ref.gff.gz)

**Comment by kandabarau** [comment]
try editing line 1974 to:

elif gene_annotation[2] == 'transcript' or gene_annotation[2] == 'mRNA':

**Comment by ryanlayer** [comment]
I will add this to the next release, thank you.

**Comment by ryanlayer** [comment]
This is fixed.
