### ISSUE TITLE
recent GFF3 has no transcript but mRNA in 3rd column

### ISSUE THREAD

**Issue by kandabarau** [ryanlayer/samplot#67]
https://github.com/ryanlayer/samplot/blob/eb39b1651b9729adf5831b0371b4eb0e20cb969d/src/samplot.py#L1974

does not work with http://ftp.ensembl.org/pub/current_gff3/homo_sapiens/Homo_sapiens.GRCh38.96.gff3.gz file

this could help:
        elif gene_annotation[2] == 'transcript' **_or gene_annotation[2] == 'mRNA'_**:

**Comment by ryanlayer** [comment]
Thanks! We fixed this in the lastest version.
