### ISSUE TITLE
matplotlib.gridspec IMPORT ERROR no module named gridspec

### ISSUE THREAD

**Issue by bibbers93** [ryanlayer/samplot#87]
Hi Ryan,

I am having a little trouble with getting samplot to work and the error I get is as follows 

```~/samplot/src/samplot.py -h
Traceback (most recent call last):
  File "/home/s1667153/samplot/src/samplot.py", line 7, in <module>
    import matplotlib.gridspec as gridspec
ImportError: No module named gridspec
```

All I am trying to do in this instance is get the help page to open up in my terminal. 

Python is loaded and my system administrator has installed (and updated) numpy, matplotlib, and pysam as detailed in your libraries file with pip. We also have yum on our system - but not conda. I see another user has sent an issue regarding matplotlib before, with your answer stating that conda should resolve this but given we don't have it at the moment, I wonder if this is subtly different/ can be overcome without conda (based on reservations of not wanting a 3rd package manager on our system)

Best, 

Ll.

**Comment by ryanlayer** [comment]
You certainly don’t need conda, it can (sometimes) simplify the process. 

What version of matplotlib lib do you have installed?

Run 

$ python
>>> import matplotlib 
>>> matplotlib.__version__

**Comment by bibbers93** [comment]
Hi,

Running those commands : maplotlib.__version__ is 0.99.1.1 

(which I see isn't 3.1.1 according to here https://matplotlib.org/)

**Comment by bibbers93** [comment]
Hi Ryan, 

so having noticed that we were installing and updating matplotlib to 3.1.1 our system default for python (2.6.6) was loading 0.99.1.1. We have since removed matplotlib from our default python, and added matplotlib v3.1.1 to our module python.3.6.5 and it seems to be working... I can get the help page open at least! :)

**Comment by ryanlayer** [comment]
Great! Let us know how it goes.

**Comment by bibbers93** [comment]
Hi Ryan, so I have a few inversions and deletions that I've got outputs for, but I have a few additional questions about samplot that I hope you don't mind answering. 

(1) is there a size limit for a SV event to be drawn? - I have a sample that contains a 40mb inversion. in running samplot I get the following error so presumably there is a SIZE limit, I just wondered what the max distance would be, and if it was possible to draw the "shoulders" of an event (where the paired/split reads run off the graph for each breakpoint) if the distance is too big. 

```Failed to save figure ./AMLQC102058N_t33.png. Region may be too large
Traceback (most recent call last):
  File "/disk/install/modules/apps/gcc/python/3.6.5/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 146, in draw_path
    self._renderer.draw_path(gc, path, transform, rgbFace)
OverflowError: In draw_path: Exceeded cell block limit
```
Secondly, 

(2) What does the ```-t``` argument take... just INS, DEL, and DUP? and am I right in thinking the ```-t``` argument doesn't change the way the plot is drawn besides having a bar/ named event across the positions defined by ```-s``` and ```-e``` 

Thanks.

**Comment by ryanlayer** [comment]
1) All "--zoom 500" to see just  +-500bp around the breakpoints
2) If you do not give the SV type, then samplot will only plot the region
between the coordinates you provided. The idea there is that you just want
too look at a region and not an SV.
