### ISSUE TITLE
Sample names rearranged

### ISSUE THREAD

**Issue by bhargava-morampalli** [ryanlayer/samplot#96]
If I give a set of bam files to samplot, the last sample's name gets assigned to the first figure and all the sample names from then gets reassigned to the next figure. 
For example: 

`samplot.py -b sample1_sorted.bam sample2_sorted.bam sample3_sorted.bam sample4_sorted.bam sample5_sorted.bam sample6_sorted.bam sample7_sorted.bam sample8_sorted.bam -o compare_all_adhesion.png -s 110000 -e 130000 -c tig00000012_pilon`

In this case (8 samples), the last label, "sample8_sorted.bam" got assigned to the first figure, label - "sample1_sorted.bam" got assigned to the 2nd figure and so on. Is this a known issue or am I making a mistake in specifying an option here?

I have tried this by explicitly specifying labels for figures and same issue arises.

**Comment by jbelyeu** [comment]
Thanks for the heads up. Will troubleshoot and respond asap

**Comment by jbelyeu** [comment]
I have not been able to recreate this error. Any chance you might be using an older version of samplot?

**Comment by drmjc** [comment]
Hi,
I can confirm this behaviour described by the OP. The rows in the plot match the order that the BAMs are supplied, but the names are misordered as described by the OP. Reproduced with 2-4 BAM files so far

I just installed samplot on 17th Jan 2020 via 
`git clone https://github.com/ryanlayer/samplot.git
cd samplot/
pip install -r requirements.txt 
`
all the best, Mark

**Comment by jbelyeu** [comment]
I appreciate the extra input. Still haven't been able to replicate the issue myself, though. Most of the recent development has been on the version of samplot available through conda (from `https://github.com/jbelyeu/samplot`), so perhaps you could try that? 

Install is simplified:
```
conda install samplot
```

**Comment by marcjwilliams1** [comment]
Hi, I'm also encountering inconsistent naming of figures even without specifying names. I'm using samplot pulled from bioconda in the last few days so should be up to date. Attached is the figure generated and here is the input command, none of the labels seem to be correct in this case.


```
samplot plot \
            -b 051IO_T_IGO_09443_AQ_12.bam \
            51BC_N_IGO_09443_AI_4.bam \
            Sample_051.bam \
            -o test.png \
            -c 17 \
            -d 100 \
            -s 37122933 \
            -e 38210011 \
            -T Homo_sapiens.GRCh37.82.sort.cancer2.gff3.gz
```

<img width="814" alt="Screen Shot 2020-05-28 at 12 41 23 PM" src="https://user-images.githubusercontent.com/9133916/83137600-586f5b00-a0e1-11ea-8d97-3229a98740de.png">

**Comment by jbelyeu** [comment]
I will look more deeply into this in the next week or two. I still have not been able to directly replicate the error but I'll try to trace it back through the code and figure out what could be the issue

**Comment by jbelyeu** [comment]
I think I found it! The issue appeared for me in a case where I didn't specify SV type. It's fixed in version 1.0.14 (should be available from conda tomorrow)

**Comment by drmjc** [comment]
nicely done

**Comment by marcjwilliams1** [comment]
Thanks! Will try it in the next few days.
