### ISSUE TITLE
samplot should have a min window size

### ISSUE THREAD

**Issue by brentp** [ryanlayer/samplot#97]
for small deletions, the extra padding percentage is not enough.
the min window size should be inferred from the fragment length distribution so we can see pairs that span small events.
Here's an example where a larger window would be helpful.
![notspan](https://user-images.githubusercontent.com/1739/74553261-3841d480-4f14-11ea-88e8-f19414e42467.png)

**Comment by brentp** [comment]
another example
![bad](https://user-images.githubusercontent.com/1739/74554744-75f42c80-4f17-11ea-952d-d68ad4c39f77.png)

**Comment by jbelyeu** [comment]
I forgot to close this when I implemented it but the default behavior now is to estimate frag length and maintain at least that for window size
