### ISSUE TITLE
insertions position are off by 1

### ISSUE THREAD

**Issue by brentp** [ryanlayer/samplot#99]
here are 2 examples. this happens in different ways depending on the insertion.
![off-by-1-too](https://user-images.githubusercontent.com/1739/74556156-a4273b80-4f1a-11ea-85be-27a6e0531129.png)
![off-by-1](https://user-images.githubusercontent.com/1739/74556157-a4bfd200-4f1a-11ea-90d1-e672cd648499.png)

**Comment by jbelyeu** [comment]
The coordinates for those insertions are chr1:232061329-232061333 and chr9:97192772-97192779, so I think the call is erroneous, not samplot. Am I wrong?
